FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim

WORKDIR /app

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app"
ENV UV_HTTP_TIMEOUT=300

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project

COPY src/ /app/src/

CMD ["python", "src/run_etl.py"]