services:
  postgres_db:
    image: postgres:15
    container_name: energy_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl_worker:
    build: 
      context: .
      dockerfile: Dockerfile.etl
    container_name: energy_etl
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    depends_on:
      postgres_db:
        condition: service_healthy

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: energy_streamlit
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data: